spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: feng_sha
logging:
  level:
    root: warn
    com.mp.dao: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      id-type: uuid

